spring.application.name=hub-backend
#spring.datasource.url=jdbc:postgresql://localhost:5432/HUB-DB
spring.datasource.url=postgresql://REDACTED_DB_USERNAME:REDACTED_DB_PASSWORD@REDACTED_DB_HOST/REDACTED_DB_NAME
spring.datasource.username=REDACTED_DB_USERNAME
spring.datasource.password=REDACTED_DB_PASSWORD
#spring.datasource.password=REDACTED_OLD_DB_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
application.security.jwt.secret-key=REDACTED_JWT_SECRET

spring.security.user.name=admin
spring.security.user.password=REDACTED_ADMIN_PASSWORD

spring.jpa.hibernate.ddl-auto=validate

# Fixes injection problem
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173



